/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Anushruth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        User = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        User.setBackground(new java.awt.Color(255, 215, 127));
        User.setFont(new java.awt.Font("Capture it", 0, 50)); // NOI18N
        User.setForeground(java.awt.Color.darkGray);
        User.setText("Personnel ID");
        User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clr(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel2.add(User);
        User.setBounds(510, 220, 330, 70);

        Password.setBackground(new java.awt.Color(255, 215, 127));
        Password.setFont(new java.awt.Font("Capture it", 0, 50)); // NOI18N
        Password.setForeground(java.awt.Color.darkGray);
        Password.setText("Password");
        Password.setEchoChar((char)0);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clr1(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Password);
        Password.setBounds(510, 320, 330, 60);

        title.setFont(new java.awt.Font("Capture it", 0, 100)); // NOI18N
        title.setText("Login");
        jPanel2.add(title);
        title.setBounds(540, 90, 280, 110);

        jButton1.setBackground(new java.awt.Color(255, 215, 127));
        jButton1.setFont(new java.awt.Font("Capture it", 0, 35)); // NOI18N
        jButton1.setForeground(java.awt.Color.darkGray);
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(590, 400, 170, 50);

        jButton2.setBackground(new java.awt.Color(255, 215, 127));
        jButton2.setFont(new java.awt.Font("Capture it", 0, 35)); // NOI18N
        jButton2.setForeground(java.awt.Color.darkGray);
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(590, 470, 170, 50);

        Login.setFont(new java.awt.Font("Capture it", 0, 11)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Login.jpg"))); // NOI18N
        Login.setText("Login");
        jPanel2.add(Login);
        Login.setBounds(0, 0, 1370, 770);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     static final String DB_URL="jdbc:mysql://localhost:3306/AMS";
     static final String USER="root";
     static final String PASS="Asranush1326";
     Connection con;
     ResultSet rs;
     Statement stmt;
    private void clr(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clr
     User.setText("");
     User.setForeground(Color.black);// TODO add your handling code here:
    }//GEN-LAST:event_clr

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void clr1(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clr1
    Password.setText("");
Password.setForeground(Color.black); 
Password.setEchoChar('*');
// TODO add your handling code here:
    }//GEN-LAST:event_clr1

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String login;
login=User.getText();
String password=Password.getText();
String usr="",pwd="";
try{
    Class.forName("java.sql.Driver");
  con=DriverManager.getConnection(DB_URL,USER,PASS);
    String sql;
    sql="SELECT PID,PWD FROM PERSONNEL WHERE PID='"+login+"'AND PWD='"+password+"';";
    stmt=con.createStatement(); 
    rs=stmt.executeQuery(sql);
    while(rs.next()){
        usr=rs.getString("PID");
        pwd=rs.getString("PWD");
    }
    if(login.equals(usr)&&password.equals(pwd)){
        if(login.charAt(0)=='D'){
           this.setVisible(true);
            Dept d=new Dept();
            d.setVisible(true);
            this.setVisible(false);
    }
        else{
         this.setVisible(true);
         perhome h=new perhome();
         h.setVisible(true);
         this.setVisible(false);
        }
    }
    else{
        JOptionPane.showMessageDialog(this,"INVALID USER OR PASSWORD");
    }
}
catch (Exception e){
    e.printStackTrace();
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(true);
            Options h=new Options();
            h.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                title.requestFocus();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField User;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
