/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import static Main.perhome.DB_URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anushruth
 */
public class pubinfo extends javax.swing.JFrame {

    /**
     * Creates new form pubinfo
     */
    public pubinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        Info.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Regiment", "Wars", "Status"
            }
        ));
        jScrollPane1.setViewportView(Info);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 180, 750, 402);

        jButton1.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 70, 120, 40);

        jButton2.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jButton2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jButton2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 650, 110, 40);

        jButton3.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jButton3.setText("Won");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(930, 220, 120, 40);

        jButton4.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jButton4.setText("Lost");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(930, 280, 120, 40);

        jButton5.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jButton5.setText("ONGOING");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(930, 340, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Russian Army Soldier Wallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) Info.getModel();
          while(model.getRowCount() > 0){
            for(int i=0;i<model.getRowCount();i++)
                model.removeRow(i);
        }
            try{
    Class.forName("java.sql.Driver");
  con=DriverManager.getConnection(DB_URL, USER, PASS);
  stmt=con.createStatement();
    String sql;
    sql="SELECT DISTINCT R.RNAME,W.WARNAME,F.STATUS FROM REGIMENT R,FOUGHT F,WARS W WHERE R.RID=F.RID AND F.WAID=W.WAID;";
    rs=stmt.executeQuery(sql);
    while(rs.next()){
        model.addRow(new Object[] {
            rs.getString(1),rs.getString(2),rs.getString(3)
        });
    }
    rs.close();
    stmt.close();
    con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(true);
            Options h=new Options();
            h.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Info.getModel();
        while(model.getRowCount() > 0){
            for(int i=0;i<model.getRowCount();i++)
                model.removeRow(i);
        }
            
            try{
                
    Class.forName("java.sql.Driver");
  con=DriverManager.getConnection(DB_URL, USER, PASS);
  stmt=con.createStatement();
    String sql;
    sql="SELECT DISTINCT R.RNAME,W.WARNAME,F.STATUS FROM REGIMENT R,FOUGHT F,WARS W WHERE R.RID=F.RID AND F.WAID=W.WAID AND F.STATUS='WON';";
    rs=stmt.executeQuery(sql);
    while(rs.next()){
        model.addRow(new Object[] {
            rs.getString(1),rs.getString(2),rs.getString(3)
        });
    }
    rs.close();
    stmt.close();
    con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 DefaultTableModel model = (DefaultTableModel) Info.getModel();
  while(model.getRowCount() > 0){
            for(int i=0;i<model.getRowCount();i++)
                model.removeRow(i);
        }
            try{
    Class.forName("java.sql.Driver");
  con=DriverManager.getConnection(DB_URL, USER, PASS);
  stmt=con.createStatement();
    String sql;
    sql="SELECT DISTINCT R.RNAME,W.WARNAME,F.STATUS FROM REGIMENT R,FOUGHT F,WARS W WHERE R.RID=F.RID AND F.WAID=W.WAID AND F.STATUS='LOST';";
    rs=stmt.executeQuery(sql);
    while(rs.next()){
        model.addRow(new Object[] {
            rs.getString(1),rs.getString(2),rs.getString(3)
        });
    }
    rs.close();
    stmt.close();
    con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 DefaultTableModel model = (DefaultTableModel) Info.getModel();
  while(model.getRowCount() > 0){
            for(int i=0;i<model.getRowCount();i++)
                model.removeRow(i);
        }
            try{
    Class.forName("java.sql.Driver");
  con=DriverManager.getConnection(DB_URL, USER, PASS);
  stmt=con.createStatement();
    String sql;
    sql="SELECT DISTINCT R.RNAME,W.WARNAME,F.STATUS FROM REGIMENT R,FOUGHT F,WARS W WHERE R.RID=F.RID AND F.WAID=W.WAID AND F.STATUS='ONG';";
    rs=stmt.executeQuery(sql);
    while(rs.next()){
        model.addRow(new Object[] {
            rs.getString(1),rs.getString(2),rs.getString(3)
        });
    }
    rs.close();
    stmt.close();
    con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
static final String DB_URL="jdbc:mysql://localhost:3306/AMS";
     static final String USER="root";
     static final String PASS="Asranush1326";
     Connection con;
     ResultSet rs;
     Statement stmt;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pubinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pubinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pubinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pubinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pubinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
